version: '3.1'

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_USERNAME: 'vaadinstart'
      POSTGRESQL_PASSWORD: 'vaadinstart'
      POSTGRESQL_DATABASE: 'stammesverwaltung'
    ports:
      - 5432:5432